// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v3.21.12
// source: web/v1/web.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWebServiceCreateWarehouse = "/web.v1.WebService/CreateWarehouse"

type WebServiceHTTPServer interface {
	// CreateWarehouse Creates a warehouse
	CreateWarehouse(context.Context, *CreateWarehouseRequest) (*CreateWarehouseResponse, error)
}

func RegisterWebServiceHTTPServer(s *http.Server, srv WebServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/warehouse", _WebService_CreateWarehouse0_HTTP_Handler(srv))
}

func _WebService_CreateWarehouse0_HTTP_Handler(srv WebServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateWarehouseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebServiceCreateWarehouse)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateWarehouse(ctx, req.(*CreateWarehouseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateWarehouseResponse)
		return ctx.Result(200, reply)
	}
}

type WebServiceHTTPClient interface {
	CreateWarehouse(ctx context.Context, req *CreateWarehouseRequest, opts ...http.CallOption) (rsp *CreateWarehouseResponse, err error)
}

type WebServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewWebServiceHTTPClient(client *http.Client) WebServiceHTTPClient {
	return &WebServiceHTTPClientImpl{client}
}

func (c *WebServiceHTTPClientImpl) CreateWarehouse(ctx context.Context, in *CreateWarehouseRequest, opts ...http.CallOption) (*CreateWarehouseResponse, error) {
	var out CreateWarehouseResponse
	pattern := "/warehouse"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWebServiceCreateWarehouse))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
