server:
  http:
    addr: 0.0.0.0:8002
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 5s
  warehouse: 0.0.0.0:8000
  robot: 0.0.0.0:8001
data:
  database:
    host: 192.168.204.134
    port: "5432"
    user: emove
    password: "668466"
    database: plan
  redis:
    host: 192.168.204.134
    port: "6379"
    password: "668466"
    db: 2
    read_timeout: 0.5s
    write_timeout: 0.5s
