server:
  grpc:
    addr: 0.0.0.0:8003
    timeout: 5s
data:
  database:
    host: 192.168.204.134
    port: "5432"
    user: emove
    password: "668466"
    database: plan
  redis:
    host: 192.168.204.134
    port: "6379"
    password: "668466"
    db: 2
    read_timeout: 2s
    write_timeout: 2s
  services:
    - name: warehouse
      addr: 0.0.0.0:8001
      timeout: 3s
    - name: robot
      addr: 0.0.0.0:8002
      timeout: 3s
