server:
  grpc:
    addr: 0.0.0.0:8001
    timeout: 5s
  http:
    addr: 0.0.0.0:9001
    timeout: 5s
data:
  database:
#    host: localhost
#    port: "3306"
    host: 192.168.204.134
    port: "5432"
    user: emove
    password: "668466"
    database: warehouse
    log_level: Info
  redis:
    host: 192.168.204.134
    port: "6379"
    password: "668466"
    db: 0
    read_timeout: 2s
    write_timeout: 2s
  event:
    addr: "amqp://emove:668466@192.168.204.134:5672/"
